#pragma once

enum class MovementType
{
	ACCELERATION_UP,
	ACCELERATION_DOWN,
	ACCELERATION_LEFT,
	ACCELERATION_RIGHT,
	MOVING_GROUND,
	STATIONARY,
	DECELERATION_UP,
	DECELERATION_DOWN,
	DECELERATION_LEFT,
	DECELERATION_RIGHT,

	MOVEMENT_MAX
};